#include "inputs.mc"
#include "signals.mc"
#include "def_op.mc"
#include "def_itypes.mc"
#include "op_RV32I.mc"
//#include "op_RV32Zifencei.mc"
#include "op_RV32Zicsr.mc"
#include "op_RV32M.mc"
